dist: jammy
sudo: required
language: python
python: "3.11"

before_install:
  - cd ${TRAVIS_BUILD_DIR}
  - nvm install 20

install:
  - npm install
  - pip3 install tox

script:
  - psql -c 'create database nostromo_test;' -U postgres
  - psql -c 'create database ripley_loch_test;' -U postgres
  - psql nostromo_test -c 'create role ripley superuser login; alter schema public owner to ripley;' -U postgres
  - psql ripley_loch_test -c 'alter schema public owner to ripley;' -U postgres
  - pip3 install -r requirements.txt
  - tox --parallel || travis_terminate 1

services:
  - postgresql
  - redis-server

notifications:
  slack:
    secure: dXLQquWc+CBMNNMN4GlFdATncu6o2yaO3vo5sVRmaLuYZWvzTJCcUifABlqB7bq1iLqVtvEborj7/48t39pXglhKhvnDRlWd6+S/ym+GC9+DfExblOLqF2IFG7TfBxugiojPKuzssgV0ezewosSq2vQFg2j3IStLMkBpa9VltOI1X6IPYOpDeVIV4MCRblpjkzrNFnbInZVrC3JfOHzzlO17DKNKjfCPBJu3OSqf8Z8mYQJzZLBmmkMp5jO4igeSFmi286IqlGT5SzRkrbsOycLq7IbVPPT+GsZAzr/HTAL99l9xFl/i6tWBWmzifKFmH4Ouukyb62BRPrF78SanTc8fhn7d1swWfll2E/I2O7QR3oBVCAMGXptiov+7PjvE2hwpXF4cL5ic381C8kkSdNWSqrp5F+uObPGMbTupM+v80hSXKb4Y4mgt+x9vZD4LLtmF5v/6uZZ/8TtwpDdlsX6hKjr/9Rx1JTl9pkMoFdsULcPDtVllG2mkEWYh4JtJ8ObAtYGeikwa1J5cAmAwXLyuW4h65QP1wPJM2RWx7TVIjRTUgFr13o2+22icXB/0FtSxhZMGXc4z6O46uq8VCAoOEw6yFjPXGpWN76+9QNFbVYJ/4XtX+q+d15U0fe1dt1ZqUfDPb+/esvpxSMFz/j5ZmrjRh2eoJzxR7JkiEDo=
