exclude = [
    ".ebextensions",
    ".git",
    ".idea",
    ".platform",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    "__pycache__",
    "*-local.py",
    "dist",
    "fixtures",
    "node_modules",
    "public",
    "src",
    "venv"
]
extend-exclude = ["config/development-local.py"]
line-length = 150
indent-width = 4

# Python version
target-version = "py311"

[lint]
select = ['ALL']

# TODO: Rules we want to enable:
# ARG002, ARG004, B006, B007, B012, B020, BLE001, C402, C403, C414, DTZ002, DTZ005, DTZ007, ERA001, FBT002, FBT003,
# G003, LOG009, PERF102, PIE800, PLR1704, PLR5501, PLW2901, PT003, PT021, PTH113, PYI024, Q004, RET502, RET503, RET504,
# RET505, RET506, RET506, RET508, RUF010, RUF015, S104, S105, S110, SIM102, SIM103, SIM105, SIM108, SIM110, SIM114,
# SIM115, SIM117, SIM118, SIM401, SIM910, SLF001, T201, TRY002, TRY300, TRY301, TRY400, TRY401, UP004, UP015, UP024,
# UP032

# Rules to ignore
ignore = [
    "ANN", "ARG001", "ARG002", "ARG004", "B006", "B007", "B012", "B020", "B023", "B904", "B905", "BLE001", "C401",
    "C402", "C403", "C414", "C416", "D10", "D212", "D213", "DTZ", "EM101", "EM102", "ERA001", "FBT002", "FBT003",
    "FIX002", "FLY002", "G003", "G004", "I001", "INP001", "LOG009", "PERF102", "PERF401", "PIE800", "PLC0206",
    "PLC1802", "PLR1704", "PLR2004", "PLR5501", "PLW0603", "PLW2901", "PT003", "PT021", "PTH", "PYI024", "Q000", "Q004",
    "RET502", "RET503", "RET504", "RET505", "RET506", "RET508", "RUF005", "RUF010", "RUF012", "RUF015", "S101", "S104",
    "S105", "S108", "S110", "S603", "S608", "SIM102", "SIM103", "SIM105", "SIM108", "SIM110", "SIM114", "SIM115",
    "SIM117", "SIM118", "SIM401", "SIM910", "SLF001", "T201", "TD002", "TD003", "TRY002", "TRY003", "TRY201",
    "TRY300", "TRY301", "TRY400", "TRY401", "UP004", "UP015", "UP024", "UP032", "W605"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pylint]
max-args = 11
max-branches = 15
max-statements = 60

[lint.mccabe]
max-complexity = 13

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.per-file-ignores]
"bea/*" = [
    "ARG", "B010", "B018", "C419", "C901", "ERA001", "PLE0704", "PLR091", "PLR1704", "PT026", "Q004", "RUF", "SIM",
    "TD004", "TRY", "UP"
]
