# Tox (https://tox.readthedocs.io/) is a tool for running tests in multiple virtualenvs.

[tox]
envlist =
    lint-py,
    lint-teena,
    lint-vue,
    build-vue,
    test
skipsdist = True

[testenv]
allowlist_externals = *

[testenv:lint-vue]
commands = npm run lint-vue {posargs}

[testenv:lint-vue-fix]
commands = npm run lint-vue-fix {posargs}

[testenv:build-vue]
commands = npm run build-vue

[testenv:test]
commands = pytest --durations=3 -W ignore::DeprecationWarning {posargs: tests}

[testenv:lint-teena]
commands = ruff check --ignore B010,B018,C417,PLE0704,PLW0211,PLR0911,RUF001,SIM116,SIM210,SIM211,UP034 {posargs:teena}

[testenv:lint-py]
commands = ruff check {posargs:ripley config consoler.py application.py scripts tests}
